spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - JwtAuthFilter
logging:
    level:
      org.springframework.cloud.gateway: DEBUG
      org.springframework.cloud.loadbalancer: DEBUG
      com.tango.gateway_service.config.JwtAuthFilter: DEBUG


server:
  port: 3390

JWT-SECRET-KEY: 6e5bc43a4f8a6562703ecc8f18fc348fdde509eab48fce875af0d03f6317bcee

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/



